services:
  - type: web
    name: django-blog
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_bcAtSNvZ65Xu@ep-mute-unit-a1eke4fi-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
